#Configuramos conexion en Spring Boot. Usuario, contraseña y BD son los mismos que en docker-compose.yml

spring.datasource.url=jdbc:postgresql://localhost:5432/gamevault
spring.datasource.username=gamevault_user
spring.datasource.password=gamevault_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Clave de al menos 64 caracteres para HS256 algoritmo. Es una clave con la que vamos a firmar digitalmente cada token:
#cualquier persona con esta clave podría falsificar tokens válidos, así que en un proyecto real esto nunca debería
#estar en texto plano en un archivo versionado en Git.
app.jwt.secret=C0stc0123!K0zm0z0510!h8bco52020Texto_solo_para_aumentar_el_numero_de_caracteres
#86400000 son 24h en milisegundos.
app.jwt.expiration-ms=86400000 


